<a href="https://colab.research.google.com/github/ahaddd-ship-it/natural-language-proccesing/blob/main/nlp8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
documents = [
    "Artificial intelligence is rapidly advancing across many fields.",
    "Data science combines statistics, computer science, and domain expertise.",
    "Computer vision allows machines to interpret and understand images.",
    "The new algorithm improved performance by a significant margin.",
    "Reinforcement learning involves agents learning from interactions with an environment."
]

In [3]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd

In [4]:
for i, document in enumerate (documents):
 print (f" D{i + 1}: {document}")

 D1: Artificial intelligence is rapidly advancing across many fields.
 D2: Data science combines statistics, computer science, and domain expertise.
 D3: Computer vision allows machines to interpret and understand images.
 D4: The new algorithm improved performance by a significant margin.
 D5: Reinforcement learning involves agents learning from interactions with an environment.

In [6]:
vectorizer = TfidfVectorizer(stop_words='english')
tfidf_matrix = vectorizer.fit_transform(documents)
print(tfidf_matrix.shape)

(5, 30)

In [10]:
print(tfidf_matrix)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 31 stored elements and shape (5, 30)>
  Coords	Values
  (0, 4)	0.4472135954999579
  (0, 14)	0.4472135954999579
  (0, 23)	0.4472135954999579
  (0, 0)	0.4472135954999579
  (0, 11)	0.4472135954999579
  (1, 7)	0.3218961114619563
  (1, 25)	0.6437922229239126
  (1, 5)	0.3218961114619563
  (1, 27)	0.3218961114619563
  (1, 6)	0.2597037559047736
  (1, 8)	0.3218961114619563
  (1, 10)	0.3218961114619563
  (2, 6)	0.3128396318588854
  (2, 29)	0.38775666010579296
  (2, 3)	0.38775666010579296
  (2, 19)	0.38775666010579296
  (2, 16)	0.38775666010579296
  (2, 28)	0.38775666010579296
  (2, 12)	0.38775666010579296
  (3, 21)	0.40824829046386296
  (3, 2)	0.40824829046386296
  (3, 13)	0.40824829046386296
  (3, 22)	0.40824829046386296
  (3, 26)	0.40824829046386296
  (3, 20)	0.40824829046386296
  (4, 24)	0.3333333333333333
  (4, 18)	0.6666666666666666
  (4, 17)	0.3333333333333333
  (4, 1)	0.3333333333333333
  (4, 15)	0.3333333333333333
  (4, 9)	0.3333333333333333

In [13]:
tfidf_df = pd.DataFrame(
    tfidf_matrix.toarray(),
    columns=vectorizer.get_feature_names_out(),
   index=["D1","D2","D3","D4","D5"]
)
tfidf_df.round(2)

,advancing,agents,algorithm,allows,artificial,combines,computer,data,domain,environment,...,margin,new,performance,rapidly,reinforcement,science,significant,statistics,understand,vision
D1,0.45,0.00,0.00,0.00,0.45,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.45,0.00,0.00,0.00,0.00,0.00,0.00
D2,0.00,0.00,0.00,0.00,0.00,0.32,0.26,0.32,0.32,0.00,...,0.00,0.00,0.00,0.00,0.00,0.64,0.00,0.32,0.00,0.00
D3,0.00,0.00,0.00,0.39,0.00,0.00,0.31,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.39,0.39
D4,0.00,0.00,0.41,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.41,0.41,0.41,0.00,0.00,0.00,0.41,0.00,0.00,0.00
D5,0.00,0.33,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.33,...,0.00,0.00,0.00,0.00,0.33,0.00,0.00,0.00,0.00,0.00

In [14]:
print(vectorizer.get_feature_names_out())

['advancing' 'agents' 'algorithm' 'allows' 'artificial' 'combines'
 'computer' 'data' 'domain' 'environment' 'expertise' 'fields' 'images'
 'improved' 'intelligence' 'interactions' 'interpret' 'involves'
 'learning' 'machines' 'margin' 'new' 'performance' 'rapidly'
 'reinforcement' 'science' 'significant' 'statistics' 'understand'
 'vision']

In [15]:
similarity_matrix = cosine_similarity(tfidf_matrix)
similarity_matrix

array([[1.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 1.        , 0.08124563, 0.        , 0.        ],
       [0.        , 0.08124563, 1.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 1.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 1.        ]])

In [17]:
similarity_df = pd.DataFrame(
similarity_matrix,
index=["D1", "D2", "D3", "D4", "D5"],
columns=["D1", "D2", "D3", "D4", "D5"]
)
similarity_df.round(3)

     D1     D2     D3   D4   D5
D1  1.0  0.000  0.000  0.0  0.0
D2  0.0  1.000  0.081  0.0  0.0
D3  0.0  0.081  1.000  0.0  0.0
D4  0.0  0.000  0.000  1.0  0.0
D5  0.0  0.000  0.000  0.0  1.0